spring.application.name=todo

# This one tells Spring where the DB is
spring.datasource.url=jdbc:sqlite:todo.db

# This one tells Spring
spring.datasource.driver-class-name=org.sqlite.JDBC

# This one tells Spring what flavor of SQL to use
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# This one tells Spring to destroy all tables and recreate them when the app starts
# Once you start to get things a bit more settled in your app you may want to change this behavior
spring.jpa.hibernate.ddl-auto=create-drop

# This one tells Spring to log the SQL queries it makes
spring.jpa.show-sql=true

# This one makes the queries logged above a bit easier to read
spring.jpa.properties.hibernate.format_sql=true